import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { AI_BADGE_TOOLTIP, AiGeneratedBadge } from "@/components/AiGeneratedBadge";

describe("AiGeneratedBadge", () => {
  it("renders a focusable label described by the OpenAI tooltip", () => {
    render(<AiGeneratedBadge />);
    const label = screen.getByText("AI-generated");
    const tooltip = screen.getByRole("tooltip");

    expect(tooltip).toHaveTextContent("Generated by an OpenAI model; every sentence cites an edge");
    expect(AI_BADGE_TOOLTIP).toBe("Generated by an OpenAI model; every sentence cites an edge");
    expect(label).toHaveAttribute("tabindex", "0");
    expect(label).toHaveAccessibleDescription(AI_BADGE_TOOLTIP);
  });
});
