import { useId } from "react";

export const AI_BADGE_TOOLTIP = "Generated by an OpenAI model; every sentence cites an edge";

/**
 * Marks text written by the Explain step. The tooltip shows on hover and keyboard focus.
 * Screen readers always get it through aria-describedby.
 */
export function AiGeneratedBadge({ model }: { model?: string | null }) {
  const tooltipId = useId();
  return (
    <span className="group relative inline-flex">
      <span
        tabIndex={0}
        aria-describedby={tooltipId}
        className="inline-flex items-center gap-1 rounded-full border border-action px-2 py-0.5 text-xs font-medium text-action"
      >
        <svg aria-hidden="true" viewBox="0 0 12 12" className="size-3" fill="currentColor">
          <path d="M6 0l1.4 4.6L12 6l-4.6 1.4L6 12 4.6 7.4 0 6l4.6-1.4z" />
        </svg>
        {model ? `AI-generated (${model})` : "AI-generated"}
      </span>
      <span
        id={tooltipId}
        role="tooltip"
        className="pointer-events-none invisible absolute top-full left-0 z-10 mt-1 w-64 rounded-lg border border-border bg-surface p-2 text-xs text-foreground opacity-0 shadow-sm transition-opacity group-focus-within:visible group-focus-within:opacity-100 group-hover:visible group-hover:opacity-100"
      >
        {AI_BADGE_TOOLTIP}
      </span>
    </span>
  );
}
